### ISSUE TITLE
one dependency in the bundle causes continous File::Spec::Win32 errors on strawberry 

### ISSUE THREAD

**Issue by LorenzoTa** [dagolden/Task-CPAN-Reporter#3]
hello,
thanks for your effort in making this bundle. I know this is not directly releted to your bundle but I'm not able to spot which one of the dozens of modules causes the issue.

`Use of uninitialized value $_[0] in string eq at D:/SCRIPTS/perl5.28-64bit/perl/lib/File/Spec/Win32.pm line 157.`

will appeared after configuring the tester env:

<pre>
...
Installing D:\SCRIPTS\perl5.28-64bit-BIS\perl\site\lib\Task\CPAN\Reporter.pm
Appending installation info to D:\SCRIPTS\perl5.28-64bit-BIS\perl\lib/perllocal.pod
  DAGOLDEN/Task-CPAN-Reporter-0.003.tar.gz
  D:\SCRIPTS\perl5.28-64bit-BIS\c\bin\gmake.exe install UNINST=1 -- OK

cpan> o conf init test_report
The goal of the CPAN Testers project (http://testers.cpan.org/) is to
test as many CPAN packages as possible on as many platforms as
possible.  This provides valuable feedback to module authors and
potential users to identify bugs or platform compatibility issues and
improves the overall quality and value of CPAN.

One way you can contribute is to send test results for each module
that you install.  If you install the CPAN::Reporter module, you have
the option to automatically generate and deliver test reports to CPAN
Testers whenever you run tests on a CPAN package.

See the CPAN::Reporter documentation for additional details and
configuration settings.  If your firewall blocks outgoing traffic,
you may need to configure CPAN::Reporter before sending reports.

 <test_report>
Generate test reports if CPAN::Reporter is installed (yes/no)? [no] yes

Use of uninitialized value $_[0] in string eq at D:/SCRIPTS/perl5.28-64bit-BIS/perl/lib/File/Spec/Win32.pm line 157, <STDIN> line 1.
Use of uninitialized value $_[0] in string eq at D:/SCRIPTS/perl5.28-64bit-BIS/perl/lib/File/Spec/Win32.pm line 157, <STDIN> line 1.
</pre>

If interested I've wrote a post with more doubts at [perlmonks.org](https://www.perlmonks.org/?node_id=1229908)

thanks

PS: I'm at your disposal for further tests

**Comment by LorenzoTa** [comment]
Hello a PR was submitted to strawberry perl portable to resolve the present issue. See [Perl-Dist-Strawberry/pull/9](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/pull/9)

So this one can be closed
thanks

**Comment by xdg** [comment]
Thanks for the update.
